// AUTO-GENERATED from data/solar_data.csv (NASA POWER climatology) - do not edit by hand.
// Each row: real monthly averages for one city. Units are in the field names.
const SOLAR_DATA = [
 {
  "city": "Damascus",
  "latitude_deg": 33.51,
  "longitude_deg": 36.29,
  "month": 1,
  "season": "winter",
  "typical_weather": "rainy",
  "ghi_kwh_m2_day": 2.78,
  "clearsky_ghi_kwh_m2_day": 3.71,
  "cloud_amount_percent": 56.4,
  "precip_mm_day": 2.22,
  "temp_C": 4.8,
  "humidity_percent": 76.0
 },
 {
  "city": "Damascus",
  "latitude_deg": 33.51,
  "longitude_deg": 36.29,
  "month": 2,
  "season": "winter",
  "typical_weather": "rainy",
  "ghi_kwh_m2_day": 3.63,
  "clearsky_ghi_kwh_m2_day": 4.76,
  "cloud_amount_percent": 56.8,
  "precip_mm_day": 2.02,
  "temp_C": 6.2,
  "humidity_percent": 72.4
 },
 {
  "city": "Damascus",
  "latitude_deg": 33.51,
  "longitude_deg": 36.29,
  "month": 3,
  "season": "winter",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 5.17,
  "clearsky_ghi_kwh_m2_day": 6.13,
  "cloud_amount_percent": 49.3,
  "precip_mm_day": 0.94,
  "temp_C": 9.6,
  "humidity_percent": 64.9
 },
 {
  "city": "Damascus",
  "latitude_deg": 33.51,
  "longitude_deg": 36.29,
  "month": 4,
  "season": "winter",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 6.4,
  "clearsky_ghi_kwh_m2_day": 7.35,
  "cloud_amount_percent": 45.6,
  "precip_mm_day": 0.59,
  "temp_C": 13.7,
  "humidity_percent": 55.9
 },
 {
  "city": "Damascus",
  "latitude_deg": 33.51,
  "longitude_deg": 36.29,
  "month": 5,
  "season": "summer",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 7.52,
  "clearsky_ghi_kwh_m2_day": 8.14,
  "cloud_amount_percent": 34.9,
  "precip_mm_day": 0.22,
  "temp_C": 18.8,
  "humidity_percent": 46.1
 },
 {
  "city": "Damascus",
  "latitude_deg": 33.51,
  "longitude_deg": 36.29,
  "month": 6,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 8.4,
  "clearsky_ghi_kwh_m2_day": 8.6,
  "cloud_amount_percent": 18.7,
  "precip_mm_day": 0.03,
  "temp_C": 23.5,
  "humidity_percent": 36.2
 },
 {
  "city": "Damascus",
  "latitude_deg": 33.51,
  "longitude_deg": 36.29,
  "month": 7,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 8.19,
  "clearsky_ghi_kwh_m2_day": 8.35,
  "cloud_amount_percent": 17.4,
  "precip_mm_day": 0.01,
  "temp_C": 26.4,
  "humidity_percent": 33.1
 },
 {
  "city": "Damascus",
  "latitude_deg": 33.51,
  "longitude_deg": 36.29,
  "month": 8,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 7.45,
  "clearsky_ghi_kwh_m2_day": 7.63,
  "cloud_amount_percent": 19.5,
  "precip_mm_day": 0.01,
  "temp_C": 26.3,
  "humidity_percent": 36.2
 },
 {
  "city": "Damascus",
  "latitude_deg": 33.51,
  "longitude_deg": 36.29,
  "month": 9,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 6.32,
  "clearsky_ghi_kwh_m2_day": 6.52,
  "cloud_amount_percent": 20.6,
  "precip_mm_day": 0.06,
  "temp_C": 23.3,
  "humidity_percent": 40.3
 },
 {
  "city": "Damascus",
  "latitude_deg": 33.51,
  "longitude_deg": 36.29,
  "month": 10,
  "season": "summer",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 4.69,
  "clearsky_ghi_kwh_m2_day": 5.1,
  "cloud_amount_percent": 36.2,
  "precip_mm_day": 0.41,
  "temp_C": 18.5,
  "humidity_percent": 47.0
 },
 {
  "city": "Damascus",
  "latitude_deg": 33.51,
  "longitude_deg": 36.29,
  "month": 11,
  "season": "winter",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 3.37,
  "clearsky_ghi_kwh_m2_day": 3.94,
  "cloud_amount_percent": 45.4,
  "precip_mm_day": 1.15,
  "temp_C": 11.4,
  "humidity_percent": 60.9
 },
 {
  "city": "Damascus",
  "latitude_deg": 33.51,
  "longitude_deg": 36.29,
  "month": 12,
  "season": "winter",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 2.62,
  "clearsky_ghi_kwh_m2_day": 3.37,
  "cloud_amount_percent": 51.5,
  "precip_mm_day": 1.83,
  "temp_C": 6.9,
  "humidity_percent": 71.3
 },
 {
  "city": "Aleppo",
  "latitude_deg": 36.2,
  "longitude_deg": 37.13,
  "month": 1,
  "season": "winter",
  "typical_weather": "rainy",
  "ghi_kwh_m2_day": 2.28,
  "clearsky_ghi_kwh_m2_day": 3.25,
  "cloud_amount_percent": 61.3,
  "precip_mm_day": 2.58,
  "temp_C": 6.0,
  "humidity_percent": 79.3
 },
 {
  "city": "Aleppo",
  "latitude_deg": 36.2,
  "longitude_deg": 37.13,
  "month": 2,
  "season": "winter",
  "typical_weather": "rainy",
  "ghi_kwh_m2_day": 3.11,
  "clearsky_ghi_kwh_m2_day": 4.3,
  "cloud_amount_percent": 60.4,
  "precip_mm_day": 2.34,
  "temp_C": 7.9,
  "humidity_percent": 77.9
 },
 {
  "city": "Aleppo",
  "latitude_deg": 36.2,
  "longitude_deg": 37.13,
  "month": 3,
  "season": "winter",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 4.57,
  "clearsky_ghi_kwh_m2_day": 5.72,
  "cloud_amount_percent": 53.5,
  "precip_mm_day": 1.42,
  "temp_C": 11.7,
  "humidity_percent": 73.1
 },
 {
  "city": "Aleppo",
  "latitude_deg": 36.2,
  "longitude_deg": 37.13,
  "month": 4,
  "season": "winter",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 5.85,
  "clearsky_ghi_kwh_m2_day": 7.01,
  "cloud_amount_percent": 50.9,
  "precip_mm_day": 1.02,
  "temp_C": 16.0,
  "humidity_percent": 67.0
 },
 {
  "city": "Aleppo",
  "latitude_deg": 36.2,
  "longitude_deg": 37.13,
  "month": 5,
  "season": "summer",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 7.0,
  "clearsky_ghi_kwh_m2_day": 7.85,
  "cloud_amount_percent": 37.3,
  "precip_mm_day": 0.67,
  "temp_C": 21.2,
  "humidity_percent": 60.1
 },
 {
  "city": "Aleppo",
  "latitude_deg": 36.2,
  "longitude_deg": 37.13,
  "month": 6,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 8.11,
  "clearsky_ghi_kwh_m2_day": 8.38,
  "cloud_amount_percent": 13.2,
  "precip_mm_day": 0.25,
  "temp_C": 26.2,
  "humidity_percent": 51.9
 },
 {
  "city": "Aleppo",
  "latitude_deg": 36.2,
  "longitude_deg": 37.13,
  "month": 7,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 8.01,
  "clearsky_ghi_kwh_m2_day": 8.15,
  "cloud_amount_percent": 7.6,
  "precip_mm_day": 0.06,
  "temp_C": 29.2,
  "humidity_percent": 51.5
 },
 {
  "city": "Aleppo",
  "latitude_deg": 36.2,
  "longitude_deg": 37.13,
  "month": 8,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 7.17,
  "clearsky_ghi_kwh_m2_day": 7.3,
  "cloud_amount_percent": 9.0,
  "precip_mm_day": 0.14,
  "temp_C": 29.2,
  "humidity_percent": 55.1
 },
 {
  "city": "Aleppo",
  "latitude_deg": 36.2,
  "longitude_deg": 37.13,
  "month": 9,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 5.86,
  "clearsky_ghi_kwh_m2_day": 6.1,
  "cloud_amount_percent": 14.3,
  "precip_mm_day": 0.42,
  "temp_C": 26.0,
  "humidity_percent": 56.4
 },
 {
  "city": "Aleppo",
  "latitude_deg": 36.2,
  "longitude_deg": 37.13,
  "month": 10,
  "season": "summer",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 4.14,
  "clearsky_ghi_kwh_m2_day": 4.62,
  "cloud_amount_percent": 35.4,
  "precip_mm_day": 0.98,
  "temp_C": 20.6,
  "humidity_percent": 56.4
 },
 {
  "city": "Aleppo",
  "latitude_deg": 36.2,
  "longitude_deg": 37.13,
  "month": 11,
  "season": "winter",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 2.91,
  "clearsky_ghi_kwh_m2_day": 3.5,
  "cloud_amount_percent": 45.6,
  "precip_mm_day": 1.63,
  "temp_C": 13.0,
  "humidity_percent": 64.2
 },
 {
  "city": "Aleppo",
  "latitude_deg": 36.2,
  "longitude_deg": 37.13,
  "month": 12,
  "season": "winter",
  "typical_weather": "rainy",
  "ghi_kwh_m2_day": 2.13,
  "clearsky_ghi_kwh_m2_day": 2.93,
  "cloud_amount_percent": 56.3,
  "precip_mm_day": 2.76,
  "temp_C": 7.7,
  "humidity_percent": 74.0
 },
 {
  "city": "Latakia",
  "latitude_deg": 35.52,
  "longitude_deg": 35.79,
  "month": 1,
  "season": "winter",
  "typical_weather": "rainy",
  "ghi_kwh_m2_day": 2.4,
  "clearsky_ghi_kwh_m2_day": 3.26,
  "cloud_amount_percent": 64.0,
  "precip_mm_day": 4.64,
  "temp_C": 14.0,
  "humidity_percent": 69.7
 },
 {
  "city": "Latakia",
  "latitude_deg": 35.52,
  "longitude_deg": 35.79,
  "month": 2,
  "season": "winter",
  "typical_weather": "rainy",
  "ghi_kwh_m2_day": 3.35,
  "clearsky_ghi_kwh_m2_day": 4.32,
  "cloud_amount_percent": 61.3,
  "precip_mm_day": 3.65,
  "temp_C": 14.4,
  "humidity_percent": 70.4
 },
 {
  "city": "Latakia",
  "latitude_deg": 35.52,
  "longitude_deg": 35.79,
  "month": 3,
  "season": "winter",
  "typical_weather": "cloudy",
  "ghi_kwh_m2_day": 4.81,
  "clearsky_ghi_kwh_m2_day": 5.71,
  "cloud_amount_percent": 55.0,
  "precip_mm_day": 1.9,
  "temp_C": 16.0,
  "humidity_percent": 71.8
 },
 {
  "city": "Latakia",
  "latitude_deg": 35.52,
  "longitude_deg": 35.79,
  "month": 4,
  "season": "winter",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 6.04,
  "clearsky_ghi_kwh_m2_day": 6.96,
  "cloud_amount_percent": 52.7,
  "precip_mm_day": 1.29,
  "temp_C": 18.0,
  "humidity_percent": 74.5
 },
 {
  "city": "Latakia",
  "latitude_deg": 35.52,
  "longitude_deg": 35.79,
  "month": 5,
  "season": "summer",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 7.19,
  "clearsky_ghi_kwh_m2_day": 7.76,
  "cloud_amount_percent": 39.7,
  "precip_mm_day": 0.78,
  "temp_C": 21.2,
  "humidity_percent": 76.1
 },
 {
  "city": "Latakia",
  "latitude_deg": 35.52,
  "longitude_deg": 35.79,
  "month": 6,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 7.9,
  "clearsky_ghi_kwh_m2_day": 8.18,
  "cloud_amount_percent": 25.2,
  "precip_mm_day": 0.37,
  "temp_C": 24.4,
  "humidity_percent": 78.3
 },
 {
  "city": "Latakia",
  "latitude_deg": 35.52,
  "longitude_deg": 35.79,
  "month": 7,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 7.64,
  "clearsky_ghi_kwh_m2_day": 7.9,
  "cloud_amount_percent": 27.8,
  "precip_mm_day": 0.11,
  "temp_C": 26.7,
  "humidity_percent": 80.4
 },
 {
  "city": "Latakia",
  "latitude_deg": 35.52,
  "longitude_deg": 35.79,
  "month": 8,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 6.88,
  "clearsky_ghi_kwh_m2_day": 7.12,
  "cloud_amount_percent": 28.1,
  "precip_mm_day": 0.23,
  "temp_C": 27.6,
  "humidity_percent": 79.0
 },
 {
  "city": "Latakia",
  "latitude_deg": 35.52,
  "longitude_deg": 35.79,
  "month": 9,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 5.77,
  "clearsky_ghi_kwh_m2_day": 6.04,
  "cloud_amount_percent": 28.6,
  "precip_mm_day": 0.77,
  "temp_C": 26.7,
  "humidity_percent": 71.7
 },
 {
  "city": "Latakia",
  "latitude_deg": 35.52,
  "longitude_deg": 35.79,
  "month": 10,
  "season": "summer",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 4.23,
  "clearsky_ghi_kwh_m2_day": 4.65,
  "cloud_amount_percent": 42.0,
  "precip_mm_day": 1.53,
  "temp_C": 24.4,
  "humidity_percent": 64.8
 },
 {
  "city": "Latakia",
  "latitude_deg": 35.52,
  "longitude_deg": 35.79,
  "month": 11,
  "season": "winter",
  "typical_weather": "rainy",
  "ghi_kwh_m2_day": 2.98,
  "clearsky_ghi_kwh_m2_day": 3.51,
  "cloud_amount_percent": 50.9,
  "precip_mm_day": 2.8,
  "temp_C": 19.9,
  "humidity_percent": 62.8
 },
 {
  "city": "Latakia",
  "latitude_deg": 35.52,
  "longitude_deg": 35.79,
  "month": 12,
  "season": "winter",
  "typical_weather": "rainy",
  "ghi_kwh_m2_day": 2.22,
  "clearsky_ghi_kwh_m2_day": 2.94,
  "cloud_amount_percent": 60.9,
  "precip_mm_day": 4.58,
  "temp_C": 15.9,
  "humidity_percent": 67.6
 },
 {
  "city": "Idlib",
  "latitude_deg": 35.93,
  "longitude_deg": 36.63,
  "month": 1,
  "season": "winter",
  "typical_weather": "rainy",
  "ghi_kwh_m2_day": 2.26,
  "clearsky_ghi_kwh_m2_day": 3.33,
  "cloud_amount_percent": 67.9,
  "precip_mm_day": 2.58,
  "temp_C": 6.0,
  "humidity_percent": 79.3
 },
 {
  "city": "Idlib",
  "latitude_deg": 35.93,
  "longitude_deg": 36.63,
  "month": 2,
  "season": "winter",
  "typical_weather": "rainy",
  "ghi_kwh_m2_day": 3.15,
  "clearsky_ghi_kwh_m2_day": 4.4,
  "cloud_amount_percent": 64.5,
  "precip_mm_day": 2.34,
  "temp_C": 7.9,
  "humidity_percent": 77.9
 },
 {
  "city": "Idlib",
  "latitude_deg": 35.93,
  "longitude_deg": 36.63,
  "month": 3,
  "season": "winter",
  "typical_weather": "cloudy",
  "ghi_kwh_m2_day": 4.57,
  "clearsky_ghi_kwh_m2_day": 5.81,
  "cloud_amount_percent": 58.8,
  "precip_mm_day": 1.42,
  "temp_C": 11.7,
  "humidity_percent": 73.1
 },
 {
  "city": "Idlib",
  "latitude_deg": 35.93,
  "longitude_deg": 36.63,
  "month": 4,
  "season": "winter",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 5.87,
  "clearsky_ghi_kwh_m2_day": 7.08,
  "cloud_amount_percent": 53.0,
  "precip_mm_day": 1.02,
  "temp_C": 16.0,
  "humidity_percent": 67.0
 },
 {
  "city": "Idlib",
  "latitude_deg": 35.93,
  "longitude_deg": 36.63,
  "month": 5,
  "season": "summer",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 7.06,
  "clearsky_ghi_kwh_m2_day": 7.88,
  "cloud_amount_percent": 38.8,
  "precip_mm_day": 0.67,
  "temp_C": 21.2,
  "humidity_percent": 60.1
 },
 {
  "city": "Idlib",
  "latitude_deg": 35.93,
  "longitude_deg": 36.63,
  "month": 6,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 7.97,
  "clearsky_ghi_kwh_m2_day": 8.34,
  "cloud_amount_percent": 17.6,
  "precip_mm_day": 0.25,
  "temp_C": 26.2,
  "humidity_percent": 51.9
 },
 {
  "city": "Idlib",
  "latitude_deg": 35.93,
  "longitude_deg": 36.63,
  "month": 7,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 7.81,
  "clearsky_ghi_kwh_m2_day": 8.06,
  "cloud_amount_percent": 12.8,
  "precip_mm_day": 0.06,
  "temp_C": 29.2,
  "humidity_percent": 51.5
 },
 {
  "city": "Idlib",
  "latitude_deg": 35.93,
  "longitude_deg": 36.63,
  "month": 8,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 7.04,
  "clearsky_ghi_kwh_m2_day": 7.27,
  "cloud_amount_percent": 13.5,
  "precip_mm_day": 0.14,
  "temp_C": 29.2,
  "humidity_percent": 55.1
 },
 {
  "city": "Idlib",
  "latitude_deg": 35.93,
  "longitude_deg": 36.63,
  "month": 9,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 5.83,
  "clearsky_ghi_kwh_m2_day": 6.17,
  "cloud_amount_percent": 19.4,
  "precip_mm_day": 0.42,
  "temp_C": 26.0,
  "humidity_percent": 56.4
 },
 {
  "city": "Idlib",
  "latitude_deg": 35.93,
  "longitude_deg": 36.63,
  "month": 10,
  "season": "summer",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 4.22,
  "clearsky_ghi_kwh_m2_day": 4.75,
  "cloud_amount_percent": 37.0,
  "precip_mm_day": 0.98,
  "temp_C": 20.6,
  "humidity_percent": 56.4
 },
 {
  "city": "Idlib",
  "latitude_deg": 35.93,
  "longitude_deg": 36.63,
  "month": 11,
  "season": "winter",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 2.95,
  "clearsky_ghi_kwh_m2_day": 3.58,
  "cloud_amount_percent": 48.5,
  "precip_mm_day": 1.63,
  "temp_C": 13.0,
  "humidity_percent": 64.2
 },
 {
  "city": "Idlib",
  "latitude_deg": 35.93,
  "longitude_deg": 36.63,
  "month": 12,
  "season": "winter",
  "typical_weather": "rainy",
  "ghi_kwh_m2_day": 2.13,
  "clearsky_ghi_kwh_m2_day": 3.0,
  "cloud_amount_percent": 61.7,
  "precip_mm_day": 2.76,
  "temp_C": 7.7,
  "humidity_percent": 74.0
 },
 {
  "city": "Homs",
  "latitude_deg": 34.73,
  "longitude_deg": 36.71,
  "month": 1,
  "season": "winter",
  "typical_weather": "cloudy",
  "ghi_kwh_m2_day": 2.42,
  "clearsky_ghi_kwh_m2_day": 3.53,
  "cloud_amount_percent": 65.2,
  "precip_mm_day": 1.76,
  "temp_C": 5.9,
  "humidity_percent": 73.1
 },
 {
  "city": "Homs",
  "latitude_deg": 34.73,
  "longitude_deg": 36.71,
  "month": 2,
  "season": "winter",
  "typical_weather": "cloudy",
  "ghi_kwh_m2_day": 3.24,
  "clearsky_ghi_kwh_m2_day": 4.6,
  "cloud_amount_percent": 63.6,
  "precip_mm_day": 1.45,
  "temp_C": 7.4,
  "humidity_percent": 69.5
 },
 {
  "city": "Homs",
  "latitude_deg": 34.73,
  "longitude_deg": 36.71,
  "month": 3,
  "season": "winter",
  "typical_weather": "cloudy",
  "ghi_kwh_m2_day": 4.76,
  "clearsky_ghi_kwh_m2_day": 6.02,
  "cloud_amount_percent": 56.9,
  "precip_mm_day": 0.92,
  "temp_C": 10.9,
  "humidity_percent": 63.5
 },
 {
  "city": "Homs",
  "latitude_deg": 34.73,
  "longitude_deg": 36.71,
  "month": 4,
  "season": "winter",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 6.07,
  "clearsky_ghi_kwh_m2_day": 7.27,
  "cloud_amount_percent": 51.5,
  "precip_mm_day": 0.53,
  "temp_C": 14.9,
  "humidity_percent": 56.2
 },
 {
  "city": "Homs",
  "latitude_deg": 34.73,
  "longitude_deg": 36.71,
  "month": 5,
  "season": "summer",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 7.23,
  "clearsky_ghi_kwh_m2_day": 8.06,
  "cloud_amount_percent": 39.0,
  "precip_mm_day": 0.33,
  "temp_C": 20.0,
  "humidity_percent": 48.4
 },
 {
  "city": "Homs",
  "latitude_deg": 34.73,
  "longitude_deg": 36.71,
  "month": 6,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 8.18,
  "clearsky_ghi_kwh_m2_day": 8.51,
  "cloud_amount_percent": 20.5,
  "precip_mm_day": 0.09,
  "temp_C": 24.3,
  "humidity_percent": 41.2
 },
 {
  "city": "Homs",
  "latitude_deg": 34.73,
  "longitude_deg": 36.71,
  "month": 7,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 8.04,
  "clearsky_ghi_kwh_m2_day": 8.25,
  "cloud_amount_percent": 17.4,
  "precip_mm_day": 0.02,
  "temp_C": 26.9,
  "humidity_percent": 40.1
 },
 {
  "city": "Homs",
  "latitude_deg": 34.73,
  "longitude_deg": 36.71,
  "month": 8,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 7.29,
  "clearsky_ghi_kwh_m2_day": 7.49,
  "cloud_amount_percent": 19.0,
  "precip_mm_day": 0.04,
  "temp_C": 26.9,
  "humidity_percent": 44.4
 },
 {
  "city": "Homs",
  "latitude_deg": 34.73,
  "longitude_deg": 36.71,
  "month": 9,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 6.08,
  "clearsky_ghi_kwh_m2_day": 6.39,
  "cloud_amount_percent": 22.5,
  "precip_mm_day": 0.18,
  "temp_C": 24.1,
  "humidity_percent": 48.2
 },
 {
  "city": "Homs",
  "latitude_deg": 34.73,
  "longitude_deg": 36.71,
  "month": 10,
  "season": "summer",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 4.43,
  "clearsky_ghi_kwh_m2_day": 4.96,
  "cloud_amount_percent": 38.3,
  "precip_mm_day": 0.47,
  "temp_C": 19.4,
  "humidity_percent": 51.9
 },
 {
  "city": "Homs",
  "latitude_deg": 34.73,
  "longitude_deg": 36.71,
  "month": 11,
  "season": "winter",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 3.11,
  "clearsky_ghi_kwh_m2_day": 3.78,
  "cloud_amount_percent": 48.7,
  "precip_mm_day": 1.01,
  "temp_C": 12.4,
  "humidity_percent": 60.4
 },
 {
  "city": "Homs",
  "latitude_deg": 34.73,
  "longitude_deg": 36.71,
  "month": 12,
  "season": "winter",
  "typical_weather": "cloudy",
  "ghi_kwh_m2_day": 2.31,
  "clearsky_ghi_kwh_m2_day": 3.19,
  "cloud_amount_percent": 60.2,
  "precip_mm_day": 1.41,
  "temp_C": 7.9,
  "humidity_percent": 69.2
 },
 {
  "city": "Daraa",
  "latitude_deg": 32.62,
  "longitude_deg": 36.1,
  "month": 1,
  "season": "winter",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 3.0,
  "clearsky_ghi_kwh_m2_day": 3.83,
  "cloud_amount_percent": 51.5,
  "precip_mm_day": 1.58,
  "temp_C": 7.6,
  "humidity_percent": 70.3
 },
 {
  "city": "Daraa",
  "latitude_deg": 32.62,
  "longitude_deg": 36.1,
  "month": 2,
  "season": "winter",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 3.79,
  "clearsky_ghi_kwh_m2_day": 4.85,
  "cloud_amount_percent": 52.5,
  "precip_mm_day": 1.58,
  "temp_C": 9.1,
  "humidity_percent": 66.8
 },
 {
  "city": "Daraa",
  "latitude_deg": 32.62,
  "longitude_deg": 36.1,
  "month": 3,
  "season": "winter",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 5.23,
  "clearsky_ghi_kwh_m2_day": 6.19,
  "cloud_amount_percent": 45.8,
  "precip_mm_day": 0.78,
  "temp_C": 12.5,
  "humidity_percent": 61.0
 },
 {
  "city": "Daraa",
  "latitude_deg": 32.62,
  "longitude_deg": 36.1,
  "month": 4,
  "season": "winter",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 6.41,
  "clearsky_ghi_kwh_m2_day": 7.36,
  "cloud_amount_percent": 41.6,
  "precip_mm_day": 0.43,
  "temp_C": 16.4,
  "humidity_percent": 53.1
 },
 {
  "city": "Daraa",
  "latitude_deg": 32.62,
  "longitude_deg": 36.1,
  "month": 5,
  "season": "summer",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 7.54,
  "clearsky_ghi_kwh_m2_day": 8.12,
  "cloud_amount_percent": 32.0,
  "precip_mm_day": 0.13,
  "temp_C": 21.2,
  "humidity_percent": 45.3
 },
 {
  "city": "Daraa",
  "latitude_deg": 32.62,
  "longitude_deg": 36.1,
  "month": 6,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 8.41,
  "clearsky_ghi_kwh_m2_day": 8.56,
  "cloud_amount_percent": 13.7,
  "precip_mm_day": 0.04,
  "temp_C": 24.6,
  "humidity_percent": 44.1
 },
 {
  "city": "Daraa",
  "latitude_deg": 32.62,
  "longitude_deg": 36.1,
  "month": 7,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 8.19,
  "clearsky_ghi_kwh_m2_day": 8.3,
  "cloud_amount_percent": 13.9,
  "precip_mm_day": 0.01,
  "temp_C": 26.5,
  "humidity_percent": 47.0
 },
 {
  "city": "Daraa",
  "latitude_deg": 32.62,
  "longitude_deg": 36.1,
  "month": 8,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 7.48,
  "clearsky_ghi_kwh_m2_day": 7.62,
  "cloud_amount_percent": 15.2,
  "precip_mm_day": 0.04,
  "temp_C": 26.4,
  "humidity_percent": 51.3
 },
 {
  "city": "Daraa",
  "latitude_deg": 32.62,
  "longitude_deg": 36.1,
  "month": 9,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 6.39,
  "clearsky_ghi_kwh_m2_day": 6.55,
  "cloud_amount_percent": 16.4,
  "precip_mm_day": 0.02,
  "temp_C": 24.5,
  "humidity_percent": 50.6
 },
 {
  "city": "Daraa",
  "latitude_deg": 32.62,
  "longitude_deg": 36.1,
  "month": 10,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 4.84,
  "clearsky_ghi_kwh_m2_day": 5.18,
  "cloud_amount_percent": 27.5,
  "precip_mm_day": 0.22,
  "temp_C": 20.8,
  "humidity_percent": 50.0
 },
 {
  "city": "Daraa",
  "latitude_deg": 32.62,
  "longitude_deg": 36.1,
  "month": 11,
  "season": "winter",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 3.54,
  "clearsky_ghi_kwh_m2_day": 4.04,
  "cloud_amount_percent": 38.4,
  "precip_mm_day": 0.67,
  "temp_C": 14.4,
  "humidity_percent": 55.9
 },
 {
  "city": "Daraa",
  "latitude_deg": 32.62,
  "longitude_deg": 36.1,
  "month": 12,
  "season": "winter",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 2.84,
  "clearsky_ghi_kwh_m2_day": 3.49,
  "cloud_amount_percent": 46.5,
  "precip_mm_day": 1.36,
  "temp_C": 9.6,
  "humidity_percent": 64.7
 },
 {
  "city": "Deir Ezzour",
  "latitude_deg": 35.34,
  "longitude_deg": 40.14,
  "month": 1,
  "season": "winter",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 2.7,
  "clearsky_ghi_kwh_m2_day": 3.33,
  "cloud_amount_percent": 45.4,
  "precip_mm_day": 0.84,
  "temp_C": 5.7,
  "humidity_percent": 70.6
 },
 {
  "city": "Deir Ezzour",
  "latitude_deg": 35.34,
  "longitude_deg": 40.14,
  "month": 2,
  "season": "winter",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 3.58,
  "clearsky_ghi_kwh_m2_day": 4.35,
  "cloud_amount_percent": 48.3,
  "precip_mm_day": 0.81,
  "temp_C": 8.2,
  "humidity_percent": 65.9
 },
 {
  "city": "Deir Ezzour",
  "latitude_deg": 35.34,
  "longitude_deg": 40.14,
  "month": 3,
  "season": "winter",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 4.93,
  "clearsky_ghi_kwh_m2_day": 5.72,
  "cloud_amount_percent": 46.1,
  "precip_mm_day": 0.72,
  "temp_C": 13.1,
  "humidity_percent": 56.5
 },
 {
  "city": "Deir Ezzour",
  "latitude_deg": 35.34,
  "longitude_deg": 40.14,
  "month": 4,
  "season": "winter",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 6.02,
  "clearsky_ghi_kwh_m2_day": 6.92,
  "cloud_amount_percent": 46.4,
  "precip_mm_day": 0.57,
  "temp_C": 18.5,
  "humidity_percent": 48.0
 },
 {
  "city": "Deir Ezzour",
  "latitude_deg": 35.34,
  "longitude_deg": 40.14,
  "month": 5,
  "season": "summer",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 7.09,
  "clearsky_ghi_kwh_m2_day": 7.71,
  "cloud_amount_percent": 36.6,
  "precip_mm_day": 0.33,
  "temp_C": 24.4,
  "humidity_percent": 39.9
 },
 {
  "city": "Deir Ezzour",
  "latitude_deg": 35.34,
  "longitude_deg": 40.14,
  "month": 6,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 8.01,
  "clearsky_ghi_kwh_m2_day": 8.2,
  "cloud_amount_percent": 13.7,
  "precip_mm_day": 0.02,
  "temp_C": 29.6,
  "humidity_percent": 30.7
 },
 {
  "city": "Deir Ezzour",
  "latitude_deg": 35.34,
  "longitude_deg": 40.14,
  "month": 7,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 7.76,
  "clearsky_ghi_kwh_m2_day": 7.87,
  "cloud_amount_percent": 10.3,
  "precip_mm_day": 0.0,
  "temp_C": 32.5,
  "humidity_percent": 29.6
 },
 {
  "city": "Deir Ezzour",
  "latitude_deg": 35.34,
  "longitude_deg": 40.14,
  "month": 8,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 7.01,
  "clearsky_ghi_kwh_m2_day": 7.11,
  "cloud_amount_percent": 10.7,
  "precip_mm_day": 0.0,
  "temp_C": 32.2,
  "humidity_percent": 31.7
 },
 {
  "city": "Deir Ezzour",
  "latitude_deg": 35.34,
  "longitude_deg": 40.14,
  "month": 9,
  "season": "summer",
  "typical_weather": "sunny",
  "ghi_kwh_m2_day": 5.85,
  "clearsky_ghi_kwh_m2_day": 5.98,
  "cloud_amount_percent": 12.3,
  "precip_mm_day": 0.02,
  "temp_C": 28.3,
  "humidity_percent": 32.9
 },
 {
  "city": "Deir Ezzour",
  "latitude_deg": 35.34,
  "longitude_deg": 40.14,
  "month": 10,
  "season": "summer",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 4.27,
  "clearsky_ghi_kwh_m2_day": 4.59,
  "cloud_amount_percent": 30.7,
  "precip_mm_day": 0.44,
  "temp_C": 22.4,
  "humidity_percent": 39.4
 },
 {
  "city": "Deir Ezzour",
  "latitude_deg": 35.34,
  "longitude_deg": 40.14,
  "month": 11,
  "season": "winter",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 3.15,
  "clearsky_ghi_kwh_m2_day": 3.55,
  "cloud_amount_percent": 35.9,
  "precip_mm_day": 0.59,
  "temp_C": 13.2,
  "humidity_percent": 55.5
 },
 {
  "city": "Deir Ezzour",
  "latitude_deg": 35.34,
  "longitude_deg": 40.14,
  "month": 12,
  "season": "winter",
  "typical_weather": "partly_cloudy",
  "ghi_kwh_m2_day": 2.45,
  "clearsky_ghi_kwh_m2_day": 2.98,
  "cloud_amount_percent": 44.3,
  "precip_mm_day": 0.82,
  "temp_C": 7.4,
  "humidity_percent": 67.0
 }
];
