# Generated by Django 6.0.5 on 2026-07-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_2fa_enabled_user_must_set_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
