# Generated by Django 6.0.5 on 2026-07-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_otp_last_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_code_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_code_last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
