# Generated by Django 6.0.6 on 2026-07-30 12:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breakers', '0002_kbs_breaker_fields'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('weather_drop', 'Weather Drop'), ('panel_fault', 'Panel Fault'), ('inverter_protection', 'Inverter Protection'), ('breaker_fault', 'Breaker Fault'), ('night_trip', 'Night Trip')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('message', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kbs_alerts', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KBSDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('facts', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kbs_decisions', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BreakerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('on', 'Switch On'), ('off', 'Switch Off')], max_length=10)),
                ('reason', models.CharField(max_length=255)),
                ('executed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('breaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kbs_actions', to='breakers.breaker')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='kbs.kbsdecision')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KBSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('observing', 'Observing'), ('active', 'Active')], default='observing', max_length=20)),
                ('power_saving', models.BooleanField(default=False)),
                ('cycle_seconds', models.PositiveIntegerField(default=300)),
                ('battery_capacity_Wh', models.FloatField(default=5000.0)),
                ('night_reserve_percent', models.FloatField(default=30.0)),
                ('stability_threshold_percent', models.FloatField(default=50.0)),
                ('event_stability_threshold_percent', models.FloatField(default=80.0)),
                ('heatsink_temp_limit_C', models.FloatField(default=70.0)),
                ('joule_deficit_limit_J', models.FloatField(default=3600000.0)),
                ('deficit_window_minutes', models.PositiveIntegerField(default=30)),
                ('max_inverter_power_W', models.FloatField(default=5000.0)),
                ('sudden_drop_fraction', models.FloatField(default=0.4)),
                ('sudden_draw_W', models.FloatField(default=1000.0)),
                ('baseline_minutes', models.PositiveIntegerField(default=10)),
                ('motor_peak_minutes', models.PositiveIntegerField(default=20)),
                ('event_prep_hours', models.FloatField(default=12.0)),
                ('day_start', models.TimeField(default=datetime.time(6, 0))),
                ('day_end', models.TimeField(default=datetime.time(18, 0))),
                ('observing_started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kbs_settings', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'KBS settings',
            },
        ),
        migrations.CreateModel(
            name='ScheduledEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_events', to='organizations.organization')),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.AddIndex(
            model_name='kbsdecision',
            index=models.Index(fields=['organization', '-created_at'], name='kbs_kbsdeci_organiz_105959_idx'),
        ),
    ]
