# Generated by Django 6.0.6 on 2026-07-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakers', '0002_kbs_breaker_fields'),
        ('kbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakeraction',
            name='countdown_s',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kbssettings',
            name='battery_low_margin_V',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='kbssettings',
            name='battery_low_voltage_V',
            field=models.FloatField(default=24.0),
        ),
        migrations.AddField(
            model_name='kbssettings',
            name='battery_shutdown_buffer_percent',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='kbssettings',
            name='pv_day_min_W',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='required_breakers',
            field=models.ManyToManyField(blank=True, related_name='required_for_events', to='breakers.breaker'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('weather_drop', 'Weather Drop'), ('panel_fault', 'Panel Fault'), ('inverter_protection', 'Inverter Protection'), ('battery_low', 'Battery Low'), ('breaker_fault', 'Breaker Fault'), ('night_trip', 'Night Trip')], max_length=30),
        ),
        migrations.AlterField(
            model_name='kbssettings',
            name='event_prep_hours',
            field=models.FloatField(default=24.0),
        ),
    ]
