# Generated by Django 6.0.6 on 2026-07-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbs', '0002_breakeraction_countdown_s_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbssettings',
            name='use_data_clock',
            field=models.BooleanField(default=False),
        ),
    ]
