# Generated by Django 6.0.6 on 2026-07-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbs', '0004_kbssettings_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbssettings',
            name='grid_present_min_V',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('weather_drop', 'Weather Drop'), ('panel_fault', 'Panel Fault'), ('inverter_protection', 'Inverter Protection'), ('battery_low', 'Battery Low'), ('grid_outage', 'Grid Outage'), ('breaker_fault', 'Breaker Fault'), ('night_trip', 'Night Trip')], max_length=30),
        ),
        migrations.AlterField(
            model_name='kbssettings',
            name='joule_deficit_limit_J',
            field=models.FloatField(default=10800000.0),
        ),
    ]
