# Generated by Django 6.0.5 on 2026-07-26 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('motor', 'Motor'), ('normal', 'Normal')], default='normal', max_length=20)),
                ('priority', models.PositiveIntegerField()),
                ('protected', models.BooleanField(default=False)),
                ('peak_load', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mean_load', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cycle_start', models.TimeField(blank=True, null=True)),
                ('cycle_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakers', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization', 'priority'],
            },
        ),
    ]
