# Generated by Django 6.0.7 on 2026-08-01 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakers', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuyaCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=64)),
                ('encrypted_client_secret', models.TextField()),
                ('region', models.CharField(choices=[('us', 'Western America'), ('eu', 'Central Europe'), ('cn', 'China'), ('in', 'India')], default='us', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tuya_credential', to='organizations.organization')),
            ],
        ),
    ]
