# Generated by Django 6.0.7 on 2026-08-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakers', '0002_tuyacredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaker',
            name='child_lock',
            field=models.BooleanField(default=False),
        ),
    ]
