# Generated by Django 6.0.5 on 2026-08-02 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakers', '0003_breaker_child_lock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('switch_on', 'Switch on'), ('switch_off', 'Switch off'), ('child_lock_on', 'Child lock engaged'), ('child_lock_off', 'Child lock released'), ('countdown_set', 'Countdown scheduled'), ('countdown_cancel', 'Countdown cancelled')], max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('kbs', 'Knowledge-based system')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('confirmed', models.BooleanField(null=True)),
                ('telemetry', models.JSONField(blank=True, null=True)),
                ('breaker_status', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breaker_actions', to=settings.AUTH_USER_MODEL)),
                ('breaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='breakers.breaker')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['breaker', '-created_at'], name='breakers_br_breaker_2c3815_idx')],
            },
        ),
    ]
