# Generated by Django 6.0.7 on 2026-08-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakers', '0004_breakeraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaker',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
