# Generated by Django 6.0.7 on 2026-08-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakers', '0006_merge_backend_kbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakerreading',
            name='child_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='breakerreading',
            name='countdown_1_s',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='breakerreading',
            name='cur_current_mA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breakerreading',
            name='cur_voltage_mV',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breakerreading',
            name='cycle_time',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='breakerreading',
            name='fault',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='breakerreading',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='breakerreading',
            name='relay_status',
            field=models.CharField(choices=[('power_off', 'Power Off'), ('power_on', 'Power On'), ('last', 'Last')], default='last', max_length=20),
        ),
    ]
