# Generated by Django 6.0.7 on 2026-08-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakers', '0007_breakerreading_child_lock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakerreading',
            name='units_resolved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='breakerstatus',
            name='units_resolved',
            field=models.BooleanField(default=True),
        ),
    ]
