# Generated by Django 6.0.5 on 2026-07-26 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('pk', models.CompositePrimaryKey('organization', 'timestamp', blank=True, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('grid_voltage_V', models.FloatField(blank=True, null=True)),
                ('grid_freq_Hz', models.FloatField(blank=True, null=True)),
                ('ac_output_voltage_V', models.FloatField(blank=True, null=True)),
                ('ac_output_freq_Hz', models.FloatField(blank=True, null=True)),
                ('ac_output_apparent_power_VA', models.FloatField(blank=True, null=True)),
                ('ac_output_active_power_W', models.FloatField(blank=True, null=True)),
                ('output_load_percent', models.FloatField(blank=True, null=True)),
                ('bus_voltage_V', models.FloatField(blank=True, null=True)),
                ('battery_voltage_V', models.FloatField(blank=True, null=True)),
                ('battery_charge_current_A', models.FloatField(blank=True, null=True)),
                ('battery_capacity_percent', models.FloatField(blank=True, null=True)),
                ('heatsink_temp_C', models.FloatField(blank=True, null=True)),
                ('pv_input_current_A', models.FloatField(blank=True, null=True)),
                ('pv_input_voltage_V', models.FloatField(blank=True, null=True)),
                ('battery_voltage_scc_V', models.FloatField(blank=True, null=True)),
                ('battery_discharge_current_A', models.FloatField(blank=True, null=True)),
                ('device_status_flags', models.CharField(blank=True, max_length=16, null=True)),
                ('battery_voltage_offset_fans_on', models.FloatField(blank=True, null=True)),
                ('eeprom_version', models.CharField(blank=True, max_length=16, null=True)),
                ('pv_charging_power_W', models.FloatField(blank=True, null=True)),
                ('device_status_flags2', models.CharField(blank=True, max_length=16, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='organizations.organization')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
